"""Add authentication schema and missing user columns

Revision ID: 808b6192c57c
Revises: 7cce0565853d
Create Date: 2025-12-17 08:37:44.239913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '808b6192c57c'
down_revision: Union[str, Sequence[str], None] = '7cce0565853d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_patient_triggers', table_name='patient_triggers')
    op.drop_table('patient_triggers')
    op.drop_index('idx_patient_strategies', table_name='patient_strategies')
    op.drop_table('patient_strategies')
    op.drop_index('idx_action_items_patient', table_name='action_items')
    op.drop_table('action_items')
    op.drop_index('idx_sessions_patient_date', table_name='sessions')
    op.drop_index('idx_sessions_status', table_name='sessions')
    op.drop_index('idx_sessions_therapist_date', table_name='sessions')
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('therapist', 'patient', 'admin', name='userrole'),
               existing_nullable=False)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'role',
               existing_type=sa.Enum('therapist', 'patient', 'admin', name='userrole'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'full_name')
    op.create_index('idx_sessions_therapist_date', 'sessions', ['therapist_id', sa.text('session_date DESC')], unique=False)
    op.create_index('idx_sessions_status', 'sessions', ['status'], unique=False)
    op.create_index('idx_sessions_patient_date', 'sessions', ['patient_id', sa.text('session_date DESC')], unique=False)
    op.create_table('action_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('task', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'assigned'::character varying"), autoincrement=False, nullable=True),
    sa.Column('assigned_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('completed_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='action_items_patient_id_fkey'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name='action_items_session_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='action_items_pkey')
    )
    op.create_index('idx_action_items_patient', 'action_items', ['patient_id', 'status', sa.text('assigned_date DESC')], unique=False)
    op.create_table('patient_strategies',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('effectiveness_rating', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('times_mentioned', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('first_introduced', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('last_mentioned', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.CheckConstraint('effectiveness_rating >= 1 AND effectiveness_rating <= 5', name='patient_strategies_effectiveness_rating_check'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='patient_strategies_patient_id_fkey'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name='patient_strategies_session_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='patient_strategies_pkey')
    )
    op.create_index('idx_patient_strategies', 'patient_strategies', ['patient_id', sa.text('last_mentioned DESC')], unique=False)
    op.create_table('patient_triggers',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('patient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('trigger', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('times_mentioned', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=True),
    sa.Column('last_mentioned', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], name='patient_triggers_patient_id_fkey'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name='patient_triggers_session_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='patient_triggers_pkey')
    )
    op.create_index('idx_patient_triggers', 'patient_triggers', ['patient_id', sa.text('last_mentioned DESC')], unique=False)
    # ### end Alembic commands ###
